import sendGrid from '@sendgrid/mail';

let baseUrl = '';

if (process.env.NODE_ENV !== 'production') {
  baseUrl = process.env.SENDGRID_DEVELOPMENT__URL;
} else {
  baseUrl = process.env.SENDGRID_PRODUCTION__URL;
}

/* eslint-disable max-len */
/**
 * @description contains utility function to send emails
 */
class SendEmail {
  /**
   * @param {string} email - email address to send the message to
   * @param {string} firstName - User's first name
   * @param {string} token - Token generated during signup
   * @returns {boolean} specifies if the email was sent successfully
   */
  static verifyMail(email, firstName, token) {
    const mail = {
      email,
      subject: 'WeTravel - User Email Verification',
      html: `'<div style="width: 90%; margin: 5em auto; box-shadow: 0 0 10px rgba(0,0,0,9);">
        <div>
          <div>
            <div style="background-color: #20ba4e; height: 3rem; width: 100%">
                <h2 style="text-align: center; color: white; padding-top: 10px;">Barefoot Nomad</h2>
            </div>
            <h4 style="text-align: center">Hi! ${firstName}</h4>
          </div>
          <div style=" padding: 0px 20px 20px 20px">
            <div>
              <p>Please verify that your email <strong>${email}</strong>have been registered by the admin</p>
              <p>Click on the button below to verify.</p>
              <button style="color: white; background-color: #20ba4e; border: none; border-radius: 10px; text-align: center; padding: 10px;"><a  href="${baseUrl}/auth/verify_email?token=${token}" style="text-decoration: none; color: white;">Verify Account</a></button>
            </div>
            <div>
              <h3 style="text-align: center">Thank you</h3>
              <h3 style="text-align: center">Please do not reply, this is an autogenerated email.</h3>
            </div>
          </div>
        </div>
      </div>`,
    };
    return this.emailSender(mail);
  }

  /**
   * This function sends an email on verification of email address
   * @param {string} email - email address to send the message to
   * @param {string} token - Token generated during signup
   * @returns {boolean} specifies if a verification email was sent to user
   * after registration
  */
  static confirmUserReg(email) {
    const mail = {
      email,
      subject: 'WeTravel - User Email Verification',
      html: `<p>Your registration has been completed<p>
      <p>Thank you for registering with WeTravel</p>
       <p> >>>
       <a href=${baseUrl}/home> Go to your profile </a> <<< </p>`
    };
    return this.emailSender(mail);
  }

  /**
   *
   * @param {object} mail - Object containing info for sending email
   * @returns {boolean} sends email to users
   */
  static async emailSender(mail) {
    sendGrid.setApiKey(process.env.SENDGRID_API_KEY);
    const msg = {
      from: process.env.mail_master,
      html: mail.html,
      subject: mail.subject,
      to: mail.email
    };
    try {
      const isEmailSent = await sendGrid.send(msg);
      if (isEmailSent) {
        return true;
      }
    } catch (error) {
      return false;
    }
  }
}
export default SendEmail;
